### ISSUE TITLE
Document gdxcc install on Windows

### ISSUE THREAD

**Issue by khaeru** [khaeru/py-gdx#9]
Installing the GAMS GDX Python API on Windows can be confusing; add these to the documentation.

**Comment by khaeru** [comment]
@ctli — could you please comment on this issue and paste your notes from our experience installing Python API on your machine? I will tidy them up and add them to the documentation.

**Comment by ctli** [comment]
The baby steps to get gdxcc working on windows:
- Install latest GAMS (to get API_34)
- Install Anaconda in default folder (it would be under \User\YourName\Anaconda3)
- Open a command prompt, activate py34, and install gdxcc manually (use conda install ... I forgot the exact command)
- Then, you should be able to use jupyter notebook to launch a browser and run a python script to process gdx files

On a different note: in windows, the latest xarray package does not like a tableau, so we had to switch to a list when batch processing multiple gdx files
